### ISSUE TITLE
batch analysis writes CSV files multiple times

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#189]
The batch analysis script processes each file for each color, and it looks like this is causing it to re-read (and rewrite) that file multiple times.

**Comment by jakebeal** [comment]
In the tests, it looks like it's leaking through to other tests as well.

**Comment by lisatiberio** [comment]
Yes, it appears that the data for each color overwrites the data from the previous color.  I can change the fopen call to open the file for appending.  However, if the original data files don't change, the user will have a constantly growing output file.  I wrote the point cloud data out to file immediately after the call to readfcs_compensated_ERF.  I remember hearing about the large amount of data. I'm not familiar with the amount of data Matlab / Octave can comfortably pass around in memory.

If I stay with the current approach with the exception of opening the file for appending instead of writing, should we mention in a message that the new data will be appended to any files with a matching name?

**Comment by jakebeal** [comment]
Could we instead refactor so that rather than doing all files for each color (reading every file K times for K colors), we instead do all colors for each file?  That way, we'd only have to read (and rewrite) each file once.

**Comment by lisatiberio** [comment]
Absolutely.  I can restructure the existing code.  The loop over the K colors is much higher up in per_color_constitutive_analysis. There a few method calls before you hit the code in process data that executes the read then outputs the data.  I didn't want to change the looping structure in case there is a reason why it's written the way it is.

**Comment by lisatiberio** [comment]
Splitting data read out of process_data and moving it outside of the loop over the K colors solves the issue of multiple reads and writes.  The unit test test_batchAnalysisOutput passes.  However the other unit test using process_data does not pass.  Having two versions of process_data does not seem like a good solution.  The better approach appears to be to remove the loop over the K colors in per_color_constitutive_analysis and try to get the calculations correct.

**Comment by jakebeal** [comment]
I agree: I think this is going to want a more thorough refactoring in order to work right.  This is exposing an architectural issue that needs better resolution.

**Comment by lisatiberio** [comment]
I'm going to need to think on this for a bit.  I'm spinning my wheels on this and not really getting anywhere.  I'm going to work on other issues tomorrow and think on this one.

**Comment by coverney** [comment]
I looked through all of the test files and was not able to find any generating CSV file test.

**Comment by coverney** [comment]
I looked through all of the tests and did not see any mention of CSV files. Where else can I see examples of the generated files?

**Comment by jakebeal** [comment]
tests/test_batchAnalysisOutput.m
or just set: TASBEConfig.set('flow.outputPointCloud','true');

**Comment by coverney** [comment]
Thank you!

**Comment by jakebeal** [comment]
Looks like this was already fixed, not sure when...
