### ISSUE TITLE
Not converged in 500 steps.

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#210]
What exactly does this mean when running a plus/minus script? It happens a lot during my analyses. How concerned should I be about this?

**Comment by jakebeal** [comment]
This warning pops up when the Gaussian mixture fit does not fit well.
It typically means that either a) a sample is poor, or b) the shape just isn't an N-component Gaussian.
Thus, it's not something to worry about, but definitely means you should look at the bincount histograms to make sure they are sane.

It would be good if we could somehow catch this and make the message be more informative, but it may not be straightforward since it comes from inside of the curve-fitting process.

**Comment by jakebeal** [comment]
Looks like this is something that should be able to be inspected with lastwarn, or possibly even by direct modification of code, since I think we may be using a library here.
