### ISSUE TITLE
Add fluorescence gating filter in batch analysis scripts

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#211]
Create capability to add a fluorescence channel filter prior to computing batch analysis statistics. This would allow one to gate out non-transfected cells for instance.

**Comment by jakebeal** [comment]
This turned out to be much more complex and involved than originally anticipated, but it is now complete.  Two changes have been added:

- A new 'RangeFilter' class allows you to manually add range-based gates to channels in a color model.
- The `add_filter(CM,filter)` function, which operates on arbitrary units has been renamed to `add_prefilter` and complemented with an `add_postfilter` function that operates on MEFL.

The tutorial now has an example of how to add a MEFL-based range filter in the batch analysis template:

    CM = add_postfilter(CM,RangeFilter('PE-Tx-Red-YG-A',[1e6 inf]));

**Comment by jakebeal** [comment]
Note that this is currently only in the develop branch; it is scheduled for the 6.0 release, since it changes fields in ColorModel.
