### ISSUE TITLE
Error using dose-response script

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#220]
Error here is here below. I am getting this error running the LacI template as well:
```
Not enough input arguments.

Error in process_data (line 28)
        sampleresults{i}{j} = compute_sample_statistics(colorModel,experiment,fileName,analysisParams,data{i}{j});

Error in transfercurve_template (line 55)
sampleresults = process_data(CM,experiment,AP);
```

**Comment by jakebeal** [comment]
This function failed to get updated when we made an update on data processing. There was a gap in the test set, so we didn't catch it there either.  Now rather than calling "process_data" and "summarize_data" you should just call "process_transfer_curve".  The tutorial template has been updated as well.  Right now, the fixes are on the develop branch; they will be included into 6.1 when it is released.
