### ISSUE TITLE
Percent on/off computations

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#226]
Per @bhwein For bimodal behaviors, we should have a way to report the fraction of cells in an "on" bucket vs. in an "off" bucket.

There should probably be two modes for this:
1. Bimodal gaussian fit, in which we find percent in high vs. low (with defaulting for "perfect" unimodals)
2. number of events above/below a fixed threshold, supplied by the user.
3. number of events above/below a fixed threshold, generated from a "global" bimodal gaussian fit.

**Comment by coverney** [comment]
For now, I am going to assume we are going with #2 from the previous comment. This threshold will be a new TASBEConfig preference that will also be in the "Optional Settings" tab in the excel template. What TASBEConfig section should this preference be in?

**Comment by jakebeal** [comment]
I think put it in the 'flow' section next to the bin ranges.

**Comment by coverney** [comment]
Would the default be 0 since we are defaulting for a perfect unimodal?

**Comment by coverney** [comment]
Here are my thoughts to fix this issue:
- In ```per_color_constitutive_analysis```, around the location when ```writeFcsPointCloudCSV``` is called, use ```data{i}``` and go through every point to determine if it is above/ below the ```onThreshold```. Calculate the on/off fractions and store them in a temp array.
- Add the fraction data into the SampleResults constructor, so it can be referenced in ```writeStatisticsCsv```
- From there include an on/off fraction column in the statistics file for batch analysis.

I am wondering if this sounds like a reasonable approach. I also have the following questions relating to this issue:
- Should we just output the on fraction (since the off fraction would be implied)?
- I looked into the ```writeFcsPointCloudCSV``` function and it seems like ```n_conditions``` and ```numberOfPerInducerFiles``` are always 1. I wonder if that is truly the case? 
- How does ```writeFcsPointCloudCSV``` deal with replicates?

**Comment by jakebeal** [comment]
That approach sounds reasonable.  With respect to the questions:
- Let's output both on fraction and off fraction, since it will be easier for biologist users.
- For the writeFcsPointCloudCSV, I think that may just be in our test cases and not in general, but I haven't checked.  Try running with a replicate and see what it does...

**Comment by jakebeal** [comment]
Sounds like there might be a bug there then?

**Comment by coverney** [comment]
Is it supposed to calculate the average between replicates and output that? Should I do that for the on/off fractions?

**Comment by coverney** [comment]
Also, I was wondering if one fraction should be calculated per sample or multiple fractions should be found for each channel.

**Comment by jakebeal** [comment]
writeFcsPointCloudCSV should be outputting precisely one CSV file per FCS file.
Replicates can't really be combined since they have different numbers of points.

With regards to fraction computation: we should compute one per SampleResult and then summarize their mean and standard deviation (arithmetic in this case, not geometric) into the ExperimentResults

**Comment by coverney** [comment]
Sounds good. I tested writeFcsPointCloudCSV again, and it actually deals with replicates just fine.

**Comment by coverney** [comment]
What group should we put values that equal the threshold?

**Comment by jakebeal** [comment]
Let's put them in the upper group; just document this in the threshold info.

**Comment by coverney** [comment]
Completed on/off fraction feature and created tests. Changes will are in pull request 340.
