### ISSUE TITLE
Add translated_channel_max to TASBEConfig for Color Translation

### ISSUE THREAD

**Issue by coverney** [TASBE/TASBEFlowAnalytics#252]
Edit TASBEConfig by adding variable for translation channel max (for the color translation model), which has a default value of 10^5.

**Comment by coverney** [comment]
I was wondering why the color translation section in TASBEConfig is commented out.

**Comment by jakebeal** [comment]
This is because we haven't yet finished converting all of the preferences to use TASBEConfig.  If you look in ColorModel.computeColorTranslations, you'll see it pulling a bunch of preferences still from the ColorModel itself, where they shouldn't really be any more.  If you want to correct that while you're at it, that would be great.

**Comment by coverney** [comment]
The CM preferences: ```CM.translation_plot``` and ```CM.noise_plot``` should also be folded into TASBEConfig.

**Comment by coverney** [comment]
Since the color translation section is back and running, should I add another config `channelMaximum` with a default value of 10^5? I could then use that config to replace `nearMax` in `computeColorTranslations`. 

Also, `CM.translation_plot` is no longer a thing, but I can still fold `CM.noise_plot` into TASBEConfig. Should that be in its own section?

**Comment by jakebeal** [comment]
For the translations, yes, that's right.
Just ignore noise_plot, however, since its future is unclear.

**Comment by jakebeal** [comment]
Fixed by #449.
