### ISSUE TITLE
Excel cancel button

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#300]
Right now, there is no way to cancel a run in Excel before Matlab finishes what it's doing.
There should be some sort of cancel button that can abort a run.

**Comment by coverney** [comment]
Just learned that VBA does not natively support multithreading, need to find another method.

**Comment by coverney** [comment]
Found a promising stack overflow page: https://stackoverflow.com/questions/5721564/multi-threading-in-vba

**Comment by coverney** [comment]
Good news: I was finally able to get some sort of multithreading working with VBA! I am still in the midst of getting it to work with the TASBESession log. After that, I want to attempt at making the cancel button.

**Comment by coverney** [comment]
I finalized the multithreading for VBA. The user can now edit the sheet while the analysis is running in the background. The TASBESession log is also able to be transferred between the "threads". 

However, I am struggling to use multithreading to create the cancel button and progress bar. The main problem with the cancel button is that I can not communicate with a thread until it completes the macro that it is supposed to run. Also, since MATLAB is run on a COM server, even if I try to kill the thread, MATLAB will keep running until it automatically finishes. I am not sure how to get into the thread and also set its MATLAB object to nothing while the COM server is doing its own thing.  

In terms of the progress bar, I tried a bunch of different techniques involving creating a second thread that is in charge of periodically outputting the TASBESession log to the master template. I still need to test out my solution once my VPN connection is working again. A potential problem I might encounter involves the two different MATLAB servers running on the two threads. I can not pass my MATLAB object into the threads, so I need to create separate objects. I am not sure if the progress bar thread will be able to obtain the updates that are going on in the separate analysis thread. If that is the case, then I might have to do multithreading in MATLAB.

**Comment by jakebeal** [comment]
Sounds like something worth digging into advice from the internet to see if others have run into "long COM job" problems before as well.

**Comment by coverney** [comment]
My newest cancel button idea didn't end up working. I would love to brainstorm with someone to get some more ideas.

**Comment by coverney** [comment]
Is there a particular reason why the log variable in TASBESession is not declared as a property? In order to access it in the event functions, I need to call ```list()```.

**Comment by jakebeal** [comment]
I believe there was some reason having to do with octave compatibility that meant that a persistent worked and a static property did not.  I can't remember the details, however.

**Comment by coverney** [comment]
I implemented the cancel button idea, and it is working quite effectively!

**Comment by coverney** [comment]
Completed first pass for this issue. It is ready for user input/testing. Changes are in next pull request (339).
