### ISSUE TITLE
Dots in input CSV filenames removed for PointCloud files

### ISSUE THREAD

**Issue by georgebzheng** [TASBE/TASBEFlowAnalytics#464]
Sending a CSV file (e.g., sample.transcriptic.aq1bt28yz7zx4q.experiment.transcriptic.r1bsqtgkytgmn_r1bsxqhkq5at9.csv) as input to TASBE will result in an output point cloud file named sampletranscripticaq1bt28yz7zx4qexperimenttranscripticr1bsqtgkytgmn_r1bsxqhkq5at9_PointCloud.csv with all dots (except for the one before file extension) removed.  This makes it harder to link the output to input during post processing.

**Comment by jakebeal** [comment]
This is an intentional behavior: all output files from TASBE have their names "sanitized" in order to remove potentially unsafe characters, which includes those with reserved meanings such as `.`.

In order to simplify the linking, though, there is a simple way to determine what the filename will be transformed to: you can call `sanitize_filename(name)` in order to find out the way that TASBE will transform the stem.
