### ISSUE TITLE
Allow user to pick figures for Excel results import

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#471]
The image results are often just way too numerous for a person's needs.
The Excel interface should let you pick which ones are actually desired, with reasonable defaults.

Follows #470

**Comment by coverney** [comment]
Backend VBA code: https://www.excel-easy.com/vba/examples/check-box.html

**Comment by coverney** [comment]
Renaming checkboxes: https://stackoverflow.com/questions/30046386/how-rename-a-checkbox-with-vba

**Comment by coverney** [comment]
A more helpful checkbox tutorial: https://wellsr.com/vba/2015/excel/complete-guide-to-excel-vba-form-control-checkboxes/

**Comment by coverney** [comment]
I figured out how to connect the checkboxes in VBA. The next steps will be
1. Renaming the checkboxes so they match with the image file names (only applicable to CM and PM)
2. Before outputting a figure check if the corresponding checkbox is selected. If so, save the figure. 
3. Consider TC and BA separately since they are all or nothing. (Basically don't even call the output figure function if the None box is selected)

**Comment by coverney** [comment]
Should this be closed?
