### ISSUE TITLE
Please update bead catalog with URCP-38-2K lot AM01 targets

### ISSUE THREAD

**Issue by kevinwkeating** [TASBE/TASBEFlowAnalytics#515]

**Comment by jakebeal** [comment]
Do you have a copy of the AM01 numbers that you can share? It should have been provided with your bottle from SpheroTech.

Lot AM01 is not currently listed in the SpheroTech online catalog of QC templates. I would guess that it is likely to match the numbers that are used for AJ02 through AL02, but it would be good to confirm that before adding it to the catalog.

In the mean time, you can check if it's at least close by just putting in AL02 instead of AM01 for your analysis.

**Comment by kevinwkeating** [comment]
Hi Jake,

I reached out to Spherotec and the AL02 and AM01 lots are actually from the
same master lot, so they will have the same MEF values. I ran an analysis
using the AJ02 target values and the color model creation ran smoothly.

Thank you,
Kevin Keating

**Comment by jakebeal** [comment]
Great!  I've added a few more that had appeared since the last update as well, and will make a patch release shortly.
