### ISSUE TITLE
Implement single cell discrimination FSC-A vs. FSC-H

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#56]

**Comment by jakebeal** [comment]
Can you please explain a bit more what you are looking for? If you're looking to do gating on FSC-A vs. FSC-H, this is already supported by changing the gating by setting the value of `channel_names` in the `AutogateParameters`

**Comment by bhwein** [comment]
Hi Jake,
It would be nice to do a FSC-A/SSC-A followed by a FSC-A/FSC-H gate. I'm not sure how to do multiple gates in sequence. Basically it would be nice to implement this extra gate: https://www.bio-rad-antibodies.com/flow-cytometry-doublet-discrimination.html
Ben

**Comment by jakebeal** [comment]
You can add any number of gates that you want using the `add_filter` function on `ColorModel`, which you can see invoked to add the gate in line 71 of the [color model template](https://github.com/TASBE/TASBEFlowAnalytics-Tutorial/blob/master/template_colormodel/make_color_model.m)

To do what you want, you can thus run `GMMGating` twice, once for each gate.
You might also try running GMMGating on all three channels at once, but I think that the simultaneous fit is less likely to get you the behavior that you are looking for, since doublet discrimination is generally a much more subtle action than debris exclusion.

If you try this out and find it works well, please let me know, as we would then want to add it as a recommended option with a template.
