### ISSUE TITLE
Fold activations seem to be extraordinarily large

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#59]
Some of my fold changes of recombinase activation are in the range of 10^5. Is this reasonable considering the bit resolution of a cytometer is not usually much more than that? BD machines typically only go up to 2.5x10^5

**Comment by jakebeal** [comment]
Can you please point to a specific example of concern? My recollection was that they were more in the range of 10^4.

**Comment by bhwein** [comment]
Hi Jake,
Here is some recent data on characterizing some gibberellin (GIB), rapalog (RAP), and abscisic acid (ABA) inducible systems. I'm going to send you a more complete powerpoint via email. The differences make sense look at the raw differences in the +/- data, but everything makes sense relatively speaking between the systems, but it just looks almost too good.
Ben

<img width="879" alt="untitled 7" src="https://user-images.githubusercontent.com/28678480/30750170-b039d9ee-9f83-11e7-9f32-0361c76c727c.png">

**Comment by jakebeal** [comment]
Was this taken on your BD machine or on the Attune?

Looking at the + vs. minus graphs, it certainly looks like the GIB minus plot is saturating low through about 2e8 CFP MEFL, and that GIB+ is saturating high above about 4e8 CFP MEFL.  The range of low ~5e2 through high ~4e8 OFP MEFL would indeed produce just the sort of value that you're seeing.  

The key question that I have, then, is whether the low saturation is going to a fractional value, rather than bottoming out at around 1-5, which is what it's supposed to do by default.

**Comment by bhwein** [comment]
Hi Jake, this was on the Attune Nxt.
Ben

**Comment by jakebeal** [comment]
Then I think this is legitimate. If you'd like to have me double-check the individual files, send them over and I can do that, but the numbers here certainly look legitimate

**Comment by bhwein** [comment]
Hi Jake,
The files are on the BTSync in the 20170910 folder. Let me know if you are confused.
Ben
