### ISSUE TITLE
Possible to perform analysis without color controls?

### ISSUE THREAD

**Issue by mjbrenner** [TASBE/TASBEFlowAnalytics#62]
Is it possible to analyze data without color controls? This could be useful for preliminary experiments when proper color control cell lines are not yet available.

If so, what alterations would need to be made?

**Comment by jakebeal** [comment]
Color controls are absolutely required for multi-color analysis, since we have to be able to make a compensation model.  Note, however, that a color control just needs to have strong expression of (only) the fluorescent molecule being quantified --- it doesn't necessarily need to be "proper" in the sense of an experimental control.

Nevertheless, it is also the case that we should be able to omit a positive control when there is only a single color, since it is used only for compensation. I will look into this.

**Comment by jakebeal** [comment]
Fixed in #66
