### ISSUE TITLE
Not converged in 500 steps.

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#74]
I get this error every now and then during plusminus characterization. What does this mean?

**Comment by bhwein** [comment]
I feel like this is typically tied to missing points on legends. Jake - would you be able to look at my newest experiment - 09272017? This a hefty experiment with multiple devices and time points. You can comment out some of them as the analysis takes a bit of time. Some devices do seem to show the four time points I've put in the script, but some only yield 2 to 3 points and the legends get heavily messed up.

**Comment by jakebeal** [comment]
This is a warning associated with making Gaussian mixture model fits on the samples, e.g., for separating "active" and "passive" components.  This is most likely to fail when the distribution looks very much unlike a two-component mixture, especially if there are few or no points in it (which would also be when there are missing elements in the graph).

**Comment by bhwein** [comment]
Some of my transfections look super good (practically unimodal sometimes). I wonder if this is the problem. Can I turn the GMM off temporarily?

**Comment by bhwein** [comment]
I've been using my analyze_plusminus3.m btw in that experiment.

**Comment by jakebeal** [comment]
If you aren't finding the GMM estimates useful, you can ignore them. If the warnings annoy you, you can turn the *warnings* off --- next time you get a warning, check the class of warning, and turn off that warning.

**Comment by bhwein** [comment]
I don't really care about the warnings. I'm just wondering if this is why I can't seem to get some of my time points to show up. Some samples I see all of them coming in, but sometimes, I only see a few and the legend gets all messed up, see here:
![diflp-aba-rec-v-cfp](https://user-images.githubusercontent.com/28678480/30999950-38153544-a4a6-11e7-9adc-b0c278c281db.png)

**Comment by jakebeal** [comment]
Ooh... that's looking ugly.  I will check that out.

**Comment by jakebeal** [comment]
OK, I've fixed the issue with the improper legends, but that was just a surface symptom. The real problem is that there were plots being judged to have no data of interest.

Looking at the mixture model fitting problem, I found that your distributions are actually best modeled by adding a third component:

    AP=setNumGaussianComponents(AP,3);`

This fits nicely, but unfortunately, the "active" estimator is then assuming that only the very highest component should be analyzed, when we want both this highest and second-highest. That's going to take a bit longer to fix.

In the mean time, there is a workaround:

    AP=setMinFractionActive(AP,0);

This includes *all* of the data, even things that are clearly too low, but at least you aren't missing anything. I've tested this out for diCre-ABA in your analyze_plusminus3.m, and it appears to be working correctly. I will leave this issue open as I continue working on the GMM fix.

**Comment by bhwein** [comment]
Yup, everything is working swimmingly :)

**Comment by bhwein** [comment]
I actually like to see the lower CFP MEFL events. Particularly for the low time point points where I don't get much expression of the CFP.

**Comment by jakebeal** [comment]
I think that I should document this feature then...

**Comment by jakebeal** [comment]
Followups split out as issues #145 and #146
